CREATE TABLE tbclientes(
 CPF VARCHAR(11),
 NOME VARCHAR(150),
 ENDERECO1 VARCHAR(60),
 ENDERECO2 VARCHAR(60),
 BAIRRO VARCHAR(60),
 CIDADE VARCHAR(70),
 ESTADO VARCHAR(60),
 CEP VARCHAR(70),
 IDADE smallint,
 SEXO VARCHAR(2),
 LIMITE_CREDITO FLOAT,
 VOLUMES_COMPRAS FLOAT,
 PRIMEIRA_COMPRA BIT(1)
);

use praticando;
ALTER TABLE tbclientes ADD PRIMARY KEY(cpf);
ALTER TABLE tbclientes ADD column (DATA_NASCIMENTO DATE);
use praticando;

INSERT INTO tbclientes(CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRAS, PRIMEIRA_COMPRA, DATA_NASCIMENTO) VALUES ("0000000000", "Daniel", "Caminho49A", "","feira 7","Feira de santana","BA", "44091656", 21, "M", 100000, 1000, 0, "2000-12-25" );
